FROM php:7.0-apache
WORKDIR /var/www/html/Jkopi

RUN apt-get update
RUN apt-get clean
RUN mkdir -p /var/www/html/Jkopi
COPY ./Jkopi/ /var/www/html/Jkopi

RUN chmod -R 777 /var/www/html/Jkopi
RUN a2enmod rewrite

RUN composer install -vvv

EXPOSE 80

CMD [ "php"]
